name: Update Contributors

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - dev
      - main

jobs:
  update-contributors:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List files
        run: ls -la

      - name: Get list of contributors
        run: |
          echo "Querying GitHub API to get contributors..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -s https://api.github.com/repos/${{ github.repository }}/contributors \
               > contributors.json

      - name: Update readme.md without deleting content
        run: |
          python3 << 'EOF'
          import json
          import os

          readme_filename = "readme.md"
          start_marker = "<!-- CONTRIBUTORS START -->"
          end_marker = "<!-- CONTRIBUTORS END -->"

          # 1. Read the list of contributors
          with open("contributors.json", "r", encoding="utf-8") as f:
              contributors = json.load(f)

          # 2. Build the section in Markdown format using HTML for images
          html_lines = [
            "<h2>Contributors</h2>",
            "<table border='1' cellspacing='0' cellpadding='5'>",
            "  <thead>",
            "    <tr>",
            "      <th>Avatar</th>",
            "      <th>Username</th>",
            "      <th>Contributions</th>",
            "    </tr>",
            "  </thead>",
            "  <tbody>"
          ]
          md_lines = ["## Contributors", ""]
          for contributor in contributors:
            row = (
              f"    <tr>"
              f"<td><img src=\"{contributor['avatar_url']}?s=50\" alt=\"Avatar\" width=\"50\" height=\"50\"></td>"
              f"<td><a href=\"{contributor['html_url']}\">{contributor['login']}</a></td>"
              f"<td>{contributor['contributions']} contributions</td>"
              f"</tr>"
            )
            html_lines.append(row)

          html_lines.append("  </tbody>")
          html_lines.append("</table>")
          new_section = "\n".join(html_lines)

          # 3. Read current readme content
          if os.path.exists(readme_filename):
              with open(readme_filename, "r", encoding="utf-8") as f:
                  content = f.read()
          else:
              content = ""

          # 4. Insert or replace the section
          if start_marker in content and end_marker in content:
              # Replace what is between the markers
              before_start, _, remainder = content.partition(start_marker)
              _, _, after_end = remainder.partition(end_marker)

              updated_content = (
                  before_start
                  + start_marker
                  + "\n"
                  + new_section
                  + "\n"
                  + end_marker
                  + after_end
              )
          else:
              # If markers do not exist, add at the end
              updated_content = (
                  content.rstrip()
                  + "\n\n"
                  + start_marker
                  + "\n"
                  + new_section
                  + "\n"
                  + end_marker
                  + "\n"
              )

          # 5. Save the updated content
          with open(readme_filename, "w", encoding="utf-8") as f:
              f.write(updated_content)
          print("readme.md updated without deleting content.")
          EOF

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add readme.md
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update contributors list in readme.md"
            git push
          else
            echo "No changes to commit."
          fi
